version: "3.9"

# This Compose file is used for development only!
# Use docker-compose.prod.yml in production using
# docker-compose -f docker-compose.yml \
#   -f docker-compose.prod.yml \
#   --env-file .env.prod \
#   up -d

# Note: The web app is run behind the NGINX reverse proxy to prevent CORS errors
#   created by teh same origin localhost. That way, both the api and web app are
#   run in debug behind the same proxy, and all requests are made through this proxy.
#   In production, the React web app will be built and served as static files by NGINX.

services:
  api:
    build:
      target: development
    ports:
      - 5000:${API_PORT}
    env_file: .env
    environment:
      FLASK_ENV: development
      FLASK_RUN_HOST: ${API_HOST}
      FLASK_RUN_PORT: ${API_PORT}
    volumes:
      - ./api:/app:ro

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    depends_on:
      - api
    ports:
      - 3000:${WEB_APP_PORT}
    env_file: .env
    volumes:
      - ./web:/app:ro
      - node_modules:/app/node_modules

  nginx:
    image: nginx:1.21.1
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - 80:${WEB_SERVER_PORT}
    env_file: .env
    volumes:
      - ./web/nginx.dev.conf.template:/etc/nginx/templates/default.conf.template:ro

  db:
    env_file: .env

# To save dependencies between `docker-compose up`s
volumes:
  node_modules:
