version: "3.9"

services:
  api:
    depends_on:
      - db
    expose:
      - "${API_PORT}"

  db:
    image: postgres:13.4-alpine
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
